language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
env:
  global:
    secure: MeOyhRufP24+LUeowN7/BtanAxnK2NJX9FpmsVBxUIpNls0RpnIG4SLwxbAnrxX69UhE1PMy0wbH3UIGW6Jw5Tx1UhnZBuEidml8DW7rlxRrMSRpZ3iyVNzOHMbL8FmwsTMWHckMAJjJZW/PlGQnP8S4s42lpvToMY34Nziyo5BxRWr3bLEq7FPHmi3Rfc0eb6gQ+XKuSOBay2qRum3TJehIwQvPd5rQUX6vyQfMUZbWeXoePxH0su4YHMqf/vmK+vY1Ouo2fCIF9SgtBeZnhSblTmAlFqnnrNj2NlWO6/ECSmf3OMpu2kTAe9MU0oghoKDKJcki3aLyCaQdoe1xEBsZ2Cks08UVLQrHLPtorI4gnrrmiKE3BYu3sYG0erTUXj0+1JXb/h05QMieyweeFBzqM+mhTmBhhsYQ9TZQuKlzlXZ7v3jBVF2PaVWqQ9VVq9tTe6rZRc/Rd55JyjaMmAEM8eAj5AyCqZJlWn4wuznx4LTBUx5o5rTmIgmul8QnhvS9bY3QKZg+ewxaBonHGqROg74PUv1oy74yvQAfwGucaKF3gIomJ9bgx4ynr41psHLmaKRooNxkkUFhuWvb5aPxOW3jEeAQX6eIDxHXldmNn6UajuGr9i2UzW+QFDNe09HLMeSVVFF3lKePKLrfROBQN/+ZsuYYcY70MuF2oZE=
